environment: prod

## Application confs
### Port
appPort: 3000

### min number pods
minReplicas: 2

### Container size (request/limits)
resources:
  limits:
    cpu: 2
    memory: 1Gi
  requests:
    cpu: 600m
    memory: 250Mi

## AWS IAM Role
### Application needs integration with AWS services (via API calls) 
arnIAMrole: "arn:aws:iam::510338013850:role/gpa-mp-poc-typeorm"

## Container image confs
image:
  tag: prod

## Enviroment variables
extraEnv: 
  - name: NODE_ENV
    value: production
  - name: DS_HOST
    value: mp-db-prod.fcd.gpa.digital
  - name: DS_PORT
    value: "5432"
  - name: DS_USER
    value: app_meuspremios
  - name: DS_PASSWORD
    valueFrom:
      secretKeyRef:
        name: gpa-mp-member-get-member-api-secrets
        key: DS_PASSWORD
  - name: DS_NAME
    value: gpameudescontoprd

## Volumes
volumes:
  - name: ecom-cert-volume
    secret:
      secretName: ecom-cert

## Volume mounts
volumeMounts:
  - mountPath: /certificado
    name: ecom-cert-volume
    readOnly: true
