environment: hlg

## Application confs
### Port
appPort: 3000

### min number pods
minReplicas: 1

### Container size (request/limits)
resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 200m
    memory: 150Mi

## AWS IAM Role
### Application needs integration with AWS services (via API calls) 
arnIAMrole: "arn:aws:iam::XXXXXXXXXXXX:role/mp-poc-typeorm"

## Container image confs
image:
  tag: hlg

## Enviroment variables
extraEnv: 
  - name: NODE_ENV
    value: homologation
  - name: DS_HOST
    value: host
  - name: DS_PORT
    value: "5432"
  - name: DS_USER
    value: user
  - name: DS_PASSWORD
    valueFrom:
      secretKeyRef:
        name: secrets
        key: DS_PASSWORD
  - name: DS_NAME
    value: dsname
